using MinerPluginToolkitV1;
using MinerPluginToolkitV1.Configs;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace XmrStak.Configs
{
    static class ConfigHelpers
    {

        public static void WriteConfigFile<T>(string filePath, T config) where T : class
        {
            var dirPath = Path.GetDirectoryName(filePath);
            if (Directory.Exists(dirPath) == false)
            {
                Directory.CreateDirectory(dirPath);
            }
            var header = "// This config file was autogenerated by NHML.";
            var confJson = JObject.FromObject(config);
            var writeStr = JsonConvert.SerializeObject(config, Formatting.Indented);
            var start = writeStr.IndexOf("{");
            var end = writeStr.LastIndexOf("}");
            writeStr = writeStr.Substring(start + 1, end - 1);
            writeStr = header + "\n" + writeStr;
            File.WriteAllText(filePath, writeStr);
        }

        private static Task CreateConfigFileTask(string binPath, string cwdPath, string commandLine, Dictionary<string, string> environmentVariables, CancellationToken stop)
        {
            var genSettingsHandle = new BenchmarkProcess(binPath, cwdPath, commandLine, environmentVariables);
            var timeoutTime = TimeSpan.FromSeconds(30);
            var delayTime = TimeSpan.FromSeconds(5);
            return MinerToolkit.WaitBenchmarkResult(genSettingsHandle, timeoutTime, delayTime, stop);
        }

        public static async Task<bool> CreateConfigFile(string configName, string binPath, string cwdPath, string commandLine, Dictionary<string, string> environmentVariables = null)
        {
            var configFilePath = Path.Combine(cwdPath, configName);
            try
            {
                using (var stopProcess = new CancellationTokenSource())
                {
                    var configCreateTask = CreateConfigFileTask(binPath, cwdPath, commandLine, environmentVariables, stopProcess.Token);
                    var start = DateTime.Now;
                    while (DateTime.Now.Subtract(start).Seconds < 34)
                    {
                        if (configCreateTask.IsCompleted) break;
                        if (File.Exists(configFilePath))
                        {
                            stopProcess.Cancel();
                            return true;
                        }
                        await Task.Delay(300);
                    }
                }
            } catch(Exception e)
            {
                Console.WriteLine($"CreateConfigFile {e.Message}");
            }
            return File.Exists(configFilePath);
        }
    }
}
