using MinerPluginToolkitV1;
using MinerPluginToolkitV1.Configs;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using NiceHashMinerLegacy.Common;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace XmrStak.Configs
{
    static class ConfigHelpers
    {

        public static void WriteConfigFile<T>(string filePath, T config) where T : class
        {
            var dirPath = Path.GetDirectoryName(filePath);
            if (Directory.Exists(dirPath) == false)
            {
                Directory.CreateDirectory(dirPath);
            }
            var header = "// This config file was autogenerated by NHML.";
            var confJson = JObject.FromObject(config);
            var writeStr = JsonConvert.SerializeObject(config, Formatting.Indented);
            var start = writeStr.IndexOf("{");
            var end = writeStr.LastIndexOf("}");
            writeStr = writeStr.Substring(start + 1, end - 1);
            writeStr = header + "\n" + writeStr;
            File.WriteAllText(filePath, writeStr);
        }

        private static Task CreateConfigFileTask(string binPath, string cwdPath, string commandLine, Dictionary<string, string> environmentVariables, CancellationToken stop)
        {
            var genSettingsHandle = new BenchmarkProcess(binPath, cwdPath, commandLine, environmentVariables);
            var timeoutTime = TimeSpan.FromSeconds(30);
            var delayTime = TimeSpan.FromSeconds(5);
            return MinerToolkit.WaitBenchmarkResult(genSettingsHandle, timeoutTime, delayTime, stop);
        }

        public static async Task<bool> CreateConfigFiles(IEnumerable<string> configNames, string binPath, string cwdPath, string commandLine, Dictionary<string, string> environmentVariables, CancellationToken stop)
        {
            var configFilePaths = configNames.Select(configName => Path.Combine(cwdPath, configName));
            try
            {
                using (var stopProcess = new CancellationTokenSource())
                using (var linkedCancelation = CancellationTokenSource.CreateLinkedTokenSource(stopProcess.Token, stop))
                {
                    var configCreateTask = CreateConfigFileTask(binPath, cwdPath, commandLine, environmentVariables, linkedCancelation.Token);
                    var start = DateTime.Now;
                    while (DateTime.Now.Subtract(start).Seconds < 34)
                    {
                        if (configCreateTask.IsCompleted) break;
                        var checkSuccess = configFilePaths.All(configFilePath => File.Exists(configFilePath));
                        if (checkSuccess)
                        {
                            stopProcess.Cancel();
                            return true;
                        }
                        await Task.Delay(300);
                    }
                }
            }
            catch (Exception e)
            {
                Logger.Error("XMR-CONFIGS", $"Creating of config file failed: {e.Message}");
            }
            var success = configFilePaths.All(configFilePath => File.Exists(configFilePath));
            return success;
        }
    }
}
