using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace XmrStak.Configs
{
    #region xmr-stak generated
    /// // generated by xmr-stak/2.10.2/aa9d88b/master/win/nvidia-amd-cpu/0

    ///*
    // * pool_address    - Pool address should be entered as "pool_address:port" (e.g "pool.ryo-currency.com:4444"). Only stratum pools are supported.
    // * wallet_address  - Your wallet, or pool login.
    // * rig_id          - Rig identifier for pool-side statistics (needs pool support).
    // * pool_password   - Can be empty in most cases or "x".
    // * use_nicehash    - Limit the nonce to 3 bytes as required by nicehash.
    // * use_tls         - This option will make us connect using Transport Layer Security.
    // * tls_fingerprint - Server's SHA256 fingerprint. If this string is non-empty then we will check the server's cert against it.
    // * pool_weight     - Pool weight is a number telling the miner how important the pool is. Miner will mine mostly at the pool
    // *                   with the highest weight, unless the pool fails. Weight must be an integer larger than 0.
    // */

    //"pool_list" :
    //[
    //	{"pool_address" : "cryptonightheavy.eu.nicehash.com:3364", "wallet_address" : "33hGFJZQAfbdzyHGqhJPvZwncDjUBdZqjW", "rig_id" : "x", "pool_password" : "x", "use_nicehash" : true, "use_tls" : false, "tls_fingerprint" : "", "pool_weight" : 1 },
    //],

    ///*
    // * Currency to mine. Supported values:
    // *
    // *    aeon7 (use this for Aeon's new PoW)
    // *    bbscoin (automatic switch with block version 3 to cryptonight_v7)
    // *    bittube (uses cryptonight_bittube2 algorithm)
    // *    freehaven
    // *    graft
    // *    haven (automatic switch with block version 3 to cryptonight_haven)
    // *    intense
    // *    masari
    // *    monero (use this to support Monero's Oct 2018 fork)
    // *    qrl - Quantum Resistant Ledger
    // *    ryo
    // *    turtlecoin
    // *    plenteum
    // *    xcash
    // *
    // * Native algorithms which do not depend on any block versions:
    // *
    // *    # 256KiB scratchpad memory
    // *    cryptonight_turtle
    // *    # 1MiB scratchpad memory
    // *    cryptonight_lite
    // *    cryptonight_lite_v7
    // *    cryptonight_lite_v7_xor (algorithm used by ipbc)
    // *    # 2MiB scratchpad memory
    // *    cryptonight
    // *    cryptonight_gpu (for Ryo's 14th of Feb fork)
    // *    cryptonight_superfast
    // *    cryptonight_v7
    // *    cryptonight_v8
    // *    cryptonight_v8_double (used by xcash)
    // *    cryptonight_v8_half (used by masari and stellite)
    // *    cryptonight_v8_reversewaltz (used by graft)
    // *    cryptonight_v8_zelerius
    // *    # 4MiB scratchpad memory
    // *    cryptonight_bittube2
    // *    cryptonight_haven
    // *    cryptonight_heavy
    // */

    //"currency" : "cryptonight_heavy",
    #endregion xmr-stak generated

#pragma warning disable IDE1006 // Naming Styles

    [Serializable]
    class MainConfig
    {
        public int call_timeout => 10;
        public int retry_time => 30;
        public int giveup_limit => 0;
        public int verbose_level => 4;
        public bool print_motd => true;
        public int h_print_time => 300;
        public object aes_override => null;
        public string use_slow_memory { get; set; } = "warn"; // SET, warn default
        public bool tls_secure_algo => true;
        public bool daemon_mode => false;
        public string output_file { get; set; } = ""; // SET maybe when running benchmarks
        public int httpd_port { get; set; } = 4000; // SET
        public string http_login => "";
        public string http_pass => "";
        public bool prefer_ipv4 => true;
    }
#pragma warning restore IDE1006 // Naming Styles
}
