using System;
using System.Collections.Generic;

namespace XmrStak.Configs
{
    #region xmr-stak generated
    /// // generated by xmr-stak/2.10.2/aa9d88b/master/win/nvidia-amd-cpu/0

    ///*
    // * pool_address    - Pool address should be entered as "pool_address:port" (e.g "pool.ryo-currency.com:4444"). Only stratum pools are supported.
    // * wallet_address  - Your wallet, or pool login.
    // * rig_id          - Rig identifier for pool-side statistics (needs pool support).
    // * pool_password   - Can be empty in most cases or "x".
    // * use_nicehash    - Limit the nonce to 3 bytes as required by nicehash.
    // * use_tls         - This option will make us connect using Transport Layer Security.
    // * tls_fingerprint - Server's SHA256 fingerprint. If this string is non-empty then we will check the server's cert against it.
    // * pool_weight     - Pool weight is a number telling the miner how important the pool is. Miner will mine mostly at the pool
    // *                   with the highest weight, unless the pool fails. Weight must be an integer larger than 0.
    // */

    //"pool_list" :
    //[
    //	{"pool_address" : "cryptonightheavy.eu.nicehash.com:3364", "wallet_address" : "33hGFJZQAfbdzyHGqhJPvZwncDjUBdZqjW", "rig_id" : "x", "pool_password" : "x", "use_nicehash" : true, "use_tls" : false, "tls_fingerprint" : "", "pool_weight" : 1 },
    //],

    ///*
    // * Currency to mine. Supported values:
    // *
    // *    aeon7 (use this for Aeon's new PoW)
    // *    bbscoin (automatic switch with block version 3 to cryptonight_v7)
    // *    bittube (uses cryptonight_bittube2 algorithm)
    // *    freehaven
    // *    graft
    // *    haven (automatic switch with block version 3 to cryptonight_haven)
    // *    intense
    // *    masari
    // *    monero (use this to support Monero's Oct 2018 fork)
    // *    qrl - Quantum Resistant Ledger
    // *    ryo
    // *    turtlecoin
    // *    plenteum
    // *    xcash
    // *
    // * Native algorithms which do not depend on any block versions:
    // *
    // *    # 256KiB scratchpad memory
    // *    cryptonight_turtle
    // *    # 1MiB scratchpad memory
    // *    cryptonight_lite
    // *    cryptonight_lite_v7
    // *    cryptonight_lite_v7_xor (algorithm used by ipbc)
    // *    # 2MiB scratchpad memory
    // *    cryptonight
    // *    cryptonight_gpu (for Ryo's 14th of Feb fork)
    // *    cryptonight_superfast
    // *    cryptonight_v7
    // *    cryptonight_v8
    // *    cryptonight_v8_double (used by xcash)
    // *    cryptonight_v8_half (used by masari and stellite)
    // *    cryptonight_v8_reversewaltz (used by graft)
    // *    cryptonight_v8_zelerius
    // *    # 4MiB scratchpad memory
    // *    cryptonight_bittube2
    // *    cryptonight_haven
    // *    cryptonight_heavy
    // */

    //"currency" : "cryptonight_heavy",
    #endregion xmr-stak generated

#pragma warning disable IDE1006 // Naming Styles
    [Serializable]
    public class PoolItem
    {
        public string pool_address { get; set; }
        public string wallet_address { get; set; }
        public string rig_id => "x";
        public string pool_password => "x";
        public bool use_nicehash => true;
        public bool use_tls => false;
        public string tls_fingerprint => "";
        public int pool_weight => 1;
    }

    [Serializable]
    public class PoolsConfig
    {
        public PoolsConfig(string url, string username, string currency)
        {
            this.pool_list = new List<PoolItem>{ new PoolItem { pool_address = url, wallet_address = username } };
            this.currency = currency;
        }

        public List<PoolItem> pool_list { get; set; }

        public string currency { get; set; }
    }
#pragma warning restore IDE1006 // Naming Styles
}
