namespace NiceHashMiner.Utils
{
    public static class Bins_Data_3rd
    {
        #region CODE_GEN STUFF // listFiles.py

        public static string[] ALL_FILES_BINS =
        {
            @"\bminer\bminer.exe",
            @"\claymore_dual\cudart64_91.dll",
            @"\claymore_dual\Data.bin",
            @"\claymore_dual\Data1a1.bin",
            @"\claymore_dual\Data1a1.bin2",
            @"\claymore_dual\Data1b1.bin",
            @"\claymore_dual\Data1b1.bin2",
            @"\claymore_dual\Data1c1.bin",
            @"\claymore_dual\Data1c1.bin2",
            @"\claymore_dual\Data1c2.bin",
            @"\claymore_dual\Data1c2.bin2",
            @"\claymore_dual\Data1d1.bin",
            @"\claymore_dual\Data1d1.bin2",
            @"\claymore_dual\Data1e1.bin",
            @"\claymore_dual\Data1e1.bin2",
            @"\claymore_dual\Data1e2.bin",
            @"\claymore_dual\Data1e2.bin2",
            @"\claymore_dual\Data1g1.bin",
            @"\claymore_dual\Data1g1.bin2",
            @"\claymore_dual\Data1g2.bin",
            @"\claymore_dual\Data1g2.bin2",
            @"\claymore_dual\Data1h1.bin",
            @"\claymore_dual\Data1h1.bin2",
            @"\claymore_dual\Data1h2.bin",
            @"\claymore_dual\Data1h2.bin2",
            @"\claymore_dual\Data1i1.bin",
            @"\claymore_dual\Data1i1.bin2",
            @"\claymore_dual\Data1j1.bin",
            @"\claymore_dual\Data1j1.bin2",
            @"\claymore_dual\EthDcrMiner64.exe",
            @"\claymore_dual\libcurl.dll",
            @"\claymore_dual\msvcr110.dll",
            @"\claymore_dual\cuda10.0\cudart64_100.dll",
            @"\claymore_dual\cuda10.0\EthDcrMiner64.exe",
            @"\claymore_dual\cuda6.5\cudart64_65.dll",
            @"\claymore_dual\cuda6.5\EthDcrMiner64.exe",
            @"\claymore_dual\cuda7.5\cudart64_75.dll",
            @"\claymore_dual\cuda7.5\EthDcrMiner64.exe",
            @"\claymore_dual\cuda8.0\cudart64_80.dll",
            @"\claymore_dual\cuda8.0\EthDcrMiner64.exe",
            @"\claymore_dual\Remote manager\EthMan.exe",
            @"\claymore_dual\Remote manager\libeay32.dll",
            @"\claymore_dual\Remote manager\ssleay32.dll",
            @"\ethlargement\OhGodAnETHlargementPill-r2.exe",
            @"\ewbf_144\cudart32_91.dll",
            @"\ewbf_144\cudart64_91.dll",
            @"\ewbf_144\miner.exe",
            @"\gminer\miner.exe",
            @"\nbminer\nbminer.exe",
            @"\nbminer\OhGodAnETHlargementPill-r2.exe",
            @"\phoenix\PhoenixMiner.exe",
            @"\teamredminer\teamredminer.exe",
            @"\trex\msvcr71.dll",
            @"\trex\t-rex.exe",
            @"\ttminer\nvml.dll",
            @"\ttminer\nvrtc-builtins64_100.dll",
            @"\ttminer\nvrtc-builtins64_101.dll",
            @"\ttminer\nvrtc-builtins64_92.dll",
            @"\ttminer\nvrtc64_100_0.dll",
            @"\ttminer\nvrtc64_101_0.dll",
            @"\ttminer\nvrtc64_92.dll",
            @"\ttminer\SubSystemDll.dll",
            @"\ttminer\TT-Miner.exe",
            @"\ttminer\Algos\AlgoEthash-C100.dll",
            @"\ttminer\Algos\AlgoEthash-C92.dll",
            @"\ttminer\Algos\AlgoEthash.dll",
            @"\ttminer\Algos\AlgoLyra2Rev3-C100.dll",
            @"\ttminer\Algos\AlgoLyra2Rev3-C92.dll",
            @"\ttminer\Algos\AlgoLyra2Rev3.dll",
            @"\ttminer\Algos\AlgoMTP-C100.dll",
            @"\ttminer\Algos\AlgoMTP-C92.dll",
            @"\ttminer\Algos\AlgoMTP.dll",
            @"\ttminer\Algos\AlgoMyrGr-C100.dll",
            @"\ttminer\Algos\AlgoMyrGr-C92.dll",
            @"\ttminer\Algos\AlgoMyrGr.dll",
            @"\ttminer\Algos\AlgoProgPoW-C100.dll",
            @"\ttminer\Algos\AlgoProgPoW-C92.dll",
            @"\ttminer\Algos\AlgoProgPoW.dll",
            @"\ttminer\Algos\AlgoUbqhash-C100.dll",
            @"\ttminer\Algos\AlgoUbqhash-C92.dll",
            @"\ttminer\Algos\AlgoUbqhash.dll",
        };

        #endregion //CODE_GEN STUFF // listFiles.py
    }
}
